steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'luceron-ai-backend-server'  # ← Must match your actual service name
  - '--source=.'
  - '--platform=managed'
  - '--allow-unauthenticated'